version: '2'
services:
    trademark-app:
        image: trademark
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://trademark-mysql:3306/trademark?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trademark-mysql:
        extends:
            file: mysql.yml
            service: trademark-mysql
